### PR TITLE
Save

### LINKED ISSUE #135: wrong error message lookup when logging in with wrong password
The backend had a change a while ago, and now the frontend doesn't show the correct error message when trying to log in using a invalid password:

Image

### LINKED ISSUE #136: invalid social media URL during speaker application doesn't scroll to error message
When applying as a speaker and trying to use an invalid social media URL, the view doesn't automatically scroll up to the error message (and thus, the error message is not visible).

### PR DESCRIPTION
**Pull request by PurpurTentakel97**
This PR introduces:
- a single response lookup
- a new save function that parses errors when not successful
- a new wrapper save function that resets unsaved changes (I mostly use that one or I comment why I use the other one)
- a Message wrapper for multiple error messages.

Sorry for this rather big PR but I think its war worth it to have one save function and error parse function. 
Is it possible for you to check the hole page? I tried to cover it and I think its working. But it would be nice if you could make sure.
thx.

Is there a way to get all possible responses?
I tried to get all responses from previous PRs.
And I also add a response if a "new" one "appears".
But I feel like I'm missing some out.
They will not be displayed. There is only a error print and a placeholder error message.
But it would be nice to catch all responses somehow.  

close #136   
close #135

### CODE REVIEW

**Review by mgerhold — COMMENTED** [review]
* I don't know whether it was caused by this PR, but in Chrome I now get a horizontal scrollbar on the mainpage (in Firefox it's okay, though).
image
* On the speaker application page, the view does not scroll up to the error messages (I don't know if you already told me that you're going to fix this or not 😅).

**Comment by PurpurTentakel97** [comment]
Should be fixed by now.

File: src/routes/dashboard/user/application/+page.svelte [hunk 1]
```diff
@@ -62,10 +63,11 @@
         }
         data.data.socials.socials = socialResult.data;
 
-        return errorQueue.length == 0;
+        return errorQueue.length === 0;
```
Comment (mgerhold) [inline src/routes/dashboard/user/application/+page.svelte:66]:
```suggestion
        return errorQueue.length ==== 0;
```
(Kappa, obviously)

File: src/routes/dashboard/user/profile/+page.svelte [hunk 2]
```diff
@@ -84,7 +88,12 @@
         const response = await save(toSave, '/api/account/change-email');
 
         if (response.success) {
-            mail = '';
+            mail       = '';
+            errorQueue = [ // assignment because of reactivity
+                ...errorQueue,
+                'Du musst deine Mail erst bestätigen damit sie hier angezeigt wird.',
```
Comment (mgerhold) [inline src/routes/dashboard/user/profile/+page.svelte:94]:
```suggestion
                'Du musst deine E-Mail-Adresse erst bestätigen, damit sie hier angezeigt wird.',
```

**Review by peddermaster2 — COMMENTED** [review]
You are using `errorQueue` everywhere, but it it more like an `errorList` or `errorArray`.
