### PR TITLE
Front page

### LINKED ISSUE #182: [BUG] The Frontend Cannot Handle `null` Values in Events
There are multiple fields in the event data that are nullable:
* `discord_url`
* `twitch_url`
* `presskit_url`
* `trailer_youtube_id`
* `schedule_visible_from`

The frontend must be able to adapt to that. For example: If the `presskit_url` is `null`, then the frontend should not show the presskit button. Currently, the frontend just crashes.
For the 2024 event, this is not important, but for new events, we have to expect that we don't have the complete data when we first publish the event.

### LINKED ISSUE #183: Adapt new year fields

### PR DESCRIPTION
**Pull request by PurpurTentakel97**
close #182 
close #183 

- adds `frontpage_date` to admin dashboard
- adds nullable values to frontpage
- adds `is_displayed_on_frontpage` to frontpage

- note: The frontpage text when `is_diaplayed_on_frontpage` differs when logged in because you can navigate directly to the dashboard.
- note: this frontend breaks the speaker tab this the corresponding backend pr.  But the admin dashboard and the frontpage works just fine. the error is not occurring when using a newer backend. So I think we can ignore it.

### CODE REVIEW

File: src/pages/year.svelte [hunk 1]
```diff
@@ -91,85 +111,164 @@
...
+
+        {#if data.year.event.is_visible_on_frontpage}
+            <Section id="Speaker">
+                <HeadlineH2 classes="headline-h2-border">Vortragende</HeadlineH2>
+                <div class="year-section-inner">
+                    {#if data.year.speakers.length > 0}
+                        <PersonArray personData={data.year.speakers}
+                                     personPopupCallback={openPersonPopup} />
+                    {:else}
+                        <TextLine classes="text-line-center">Sei gespannt welche Speaker in den nächsten Tagen hier auf
```
Comment (mgerhold) [inline src/pages/year.svelte:195]:
```suggestion
                        <TextLine classes="text-line-center">Sei gespannt, welche Speaker in den nächsten Tagen hier auf
```

File: src/pages/year.svelte [hunk 2]
```diff
@@ -91,85 +111,164 @@
...
+
+        {#if data.year.event.is_visible_on_frontpage}
+            <Section id="Team">
+                <HeadlineH2 classes="headline-h2-border">Team</HeadlineH2>
+                <div class="year-section-inner">
+                    {#if data.year.team_members.length > 0}
+                        <PersonArray personData={data.year.team_members}
+                                     personPopupCallback={openPersonPopup} />
+                    {:else}
+                        <TextLine classes="text-line-center">Sei gespannt welche Team Member in den nächsten Tagen hier
```
Comment (mgerhold) [inline src/pages/year.svelte:229]:
```suggestion
                        <TextLine classes="text-line-center">Sei gespannt welche, Team Member in den nächsten Tagen hier
```

File: src/pages/year.svelte [hunk 3]
```diff
@@ -91,85 +111,164 @@
...
+
+        {#if data.year.event.is_visible_on_frontpage}
+            <Section id="Schedule">
+                <HeadlineH2 classes="headline-h2-border">Plan</HeadlineH2>
+                {#if data.year.talks.length > 0}
+                    <div class="center-styled-link">
+                        <StyledLink
+                              classes="styled-link-white"
+                              href={apiUrl(`/events/${data.year.event.year}/ics`)}
+                              title="Klicke um den Ablaufplan als ICS-Datei herunter zu laden"
```
Comment (mgerhold) [inline src/pages/year.svelte:245]:
```suggestion
                              title="Klicke, um den Ablaufplan als ICS-Datei herunterzuladen"
```

File: src/pages/year.svelte [hunk 4]
```diff
@@ -91,85 +111,164 @@
...
+                            />
+                            <Schedule
+                                  schedule={days.special}
+                                  speakers={data.year.speakers}
+                                  personPopupCallback={openPersonPopup}
+                            />
+                        {/each}
+                    </div>
+                {:else}
+                    <TextLine classes="text-line-center">Sei gespannt welche Team Member in den nächsten Tagen hier
```
Comment (mgerhold) [inline src/pages/year.svelte:266]:
```suggestion
                    <TextLine classes="text-line-center">Sei gespannt, welche Vorträge in den nächsten Tagen hier
```

**Review by mgerhold — APPROVED** [review]
