### PR TITLE
Response lookup

### LINKED ISSUE #147: Response Key
Add `CANNOT_DELETE_ASSIGNED_TIME_SLOTS` to response lookup

### LINKED ISSUE #152: Unknown Error when Trying to Submit Talk without Tags or Durations
When I try to submit a talk, but don't enable any tags or possible durations, the error messages of the backend don't seem to get handled correctly:

Image

Of course, it's correct that this doesn't work, but the error message is wrong.

### PR DESCRIPTION
**Pull request by PurpurTentakel97**
- add some response lookup keys
- add '' for better reading of response key error print
- fix some type errors that magickly appears in this web universe. 🙈 

close #152 
close #147

### CODE REVIEW

File: src/lookup/responseLookup.ts [hunk 1]
```diff
@@ -46,14 +46,19 @@ const lookup: ResponseDict = {
...
     // talk
-    TALK_ALREADY_APPROVED: 'Der Talk ist bereits freigegeben',
-    TALK_NOT_FOUND:        'Da haben wir wohl diesen Talk verlegt. Vielleicht finden wir ihn bald wieder.',
-    DUPLICATE_TALK:        'Diesen Talk gibt es bereits',
+    TALK_ALREADY_APPROVED:                         'Der Talk ist bereits freigegeben.',
+    TALK_NOT_FOUND:                                'Da haben wir wohl diesen Talk verlegt. Vielleicht finden wir ihn bald wieder.',
+    DUPLICATE_TALK:                                'Diesen Talk gibt es bereits.',
+    'The title field is required.':                'Das Feld \'Titel\' ist erforderlich.',
+    'The description field is required.':          'Das Feld \'Beschreibung\' ist erforderlich.',
+    'The tag_ids.* field is required.':            'Das Feld \'Tags\' ist erforderlich.',
```
Comment (mgerhold) [inline src/lookup/responseLookup.ts:54]: Since this is a user-facing message, I think we should be a bit more user-friendly here.
```suggestion
    'The tag_ids.* field is required.':            'Wähle durch Anklicken mindestens einen Tag aus, der zu deinem Vortrag passt.',
```

File: src/lookup/responseLookup.ts [hunk 2]
```diff
@@ -46,14 +46,19 @@ const lookup: ResponseDict = {
...
+    'The possible_durations.* field is required.': 'Das Feld \'Vortragslänge in Minuten\' ist erforderlich.',
```
Comment (mgerhold) [inline src/lookup/responseLookup.ts:55]:
```suggestion
    'The possible_durations.* field is required.': 'Wähle bitte eine oder mehrere mögliche Vortragsdauern aus.',
```

File: src/lookup/responseLookup.ts [hunk 3]
```diff
@@ -46,14 +46,19 @@ const lookup: ResponseDict = {
...
 
     // time slots
-    TIME_SLOTS_OVERLAP:         'Mindestens 2 Vortragszeiten überlappen sich.',
-    TIME_SLOT_ALREADY_OCCUPIED: 'Dieser Slot ist bereits vergeben.',
-    TIME_SLOT_INVALID_DURATION: 'Dieser Slot stimmt nicht mit den gewünschten Längen überein',
+    TIME_SLOTS_OVERLAP:                'Mindestens 2 Vortragszeiten überlappen sich.',
+    TIME_SLOT_ALREADY_OCCUPIED:        'Dieser Slot ist bereits vergeben.',
+    TIME_SLOT_INVALID_DURATION:        'Dieser Slot stimmt nicht mit den gewünschten Längen überein',
+    CANNOT_DELETE_ASSIGNED_TIME_SLOTS: 'Es ist nicht möglich Time Slots editieren, da einige Slots schon zugewiesen sind.',
```
Comment (mgerhold) [inline src/lookup/responseLookup.ts:61]:
```suggestion
    CANNOT_DELETE_ASSIGNED_TIME_SLOTS: 'Es ist nicht möglich, Time Slots zu editieren, da einige Slots schon zugewiesen sind.',
```

**Review by mgerhold — CHANGES_REQUESTED** [review]

**Review by mgerhold — APPROVED** [review]
